language: node_js
node_js:
- 8
script:
- yarn lint
- yarn build
deploy:
  provider: script
  script: yarn release
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - EXTENSION_ID=beoakkifjokgdckjcdlbdfmacaefdfhh
  - secure: tZ1UJGrUvjCwHSP1QA/vowWmmEhvFhL3ksW8ptedzeuWYsCWD1wKoNHNzKp/ktoWpssXIgwLas0tZ2xsAk6yTWkLUeak1ZeuoeyS31Nm9Go+U+Zi2lmsKZ4NLKBNUT4fnxmZzsBwRz50Jbz9ObsWdl420SzQCG8hJSBgfiMNOWmKF9DJDc9GxK3+5tkYw5AowyPDvyoFYpISVUEFNpxATwWYAhiwYO/xRcNaiYoVvsyFMgKlbEKfZF01V0ECmeDr4c0bDG7Lwi8DIFLH6GQVUQKF/SEgcJCCgOpyr7bTyJSRkIiVd6SgCZ/b3G3PdICgo809iFIzIH/FMgVxV98CBvZVciSAGAd1e5exzf848Tpo10WYP+IezqPbIxdxv8uqrxTLh1b7tS2D+zo04bikR+T6QDkbXBBojM5/I0pymqlnbQJLwyEyKtnKRTh2sxisXos12Ud4oPEJ8bM0CNcP2/xvpSwR/94qSaXKVIbqb4GetbNGXgVIffIhExd5Rwenvj9p2jNAbeoADNuvbaROvN8hZT/r7L/w54XgEgnntSIp4HTZfyF/CClUaiewSgOcY8u2gt5ykcUfRt+y5WocggKMpXFzMypwtf0xNr7bEsE/BboqJBy4Ib48d9RW8dD6bhznx6EICnzsOWDyjTtTGlEgmBKyoQMOBQLYwboEo2E=
  - secure: TtL3Xlc9HUzdOpARhtQmFyVOBVkAqIFI16101etxf3Oac+dn3XlVry4gNHb8szHmeV4dCNyMvOsFvUqQxagqeXH0/UHmq+Oa/r1ijEqu+WSO5kDIQSSX4aenNVis4v69cP2Z1JjZezeB7gLigCe3BhjdqM8sod9omVeIcu6k2BM5wYRxUikuxNCCbCdnesHC98zKR+eU7iVtXmvs2edagGx/Nzp+PQnBDQBwafquLyQMcw7PClBFUGmu5uDQkT4d1+iPYB8sWswV24BUikPbz+zIdW+Ph9IFKabjcPq9gJD53so3bg8D7/h+jwjaWNKNNuNDMtfuYjAqDe0H9Nke+/voqFWFYuMO6xLt4CZ7QQy/tyTEfsaLWNDsxfe0ayZtsAbddJ1rCjxwz15R7JC2DAR7PrOZ4C6RLRrl4Pm+3AKOTuVb3Y30FJk6SaW8p0uhguIR7pJ8ERYy/5u8P3MrubloooQPkzYv5YfRYz2k32SkOd/FZ5SszrcC8wHJXvyNvYPjxpO6L2sqNaLiOERSi01t1ypCTVZuHcDDllEKTDeGWDMyxAvA/HPyyEq/zmnH0ZSwfdrEUTbOjAG3ulno2hBHN1nSG22u8AjFqZNkjjKYBUWw0MxwhhHtt0yz75GlSFiZnTefMCHtHLI/I1GARGUgqyX4fsFxW+G/mm4AJBE=
  - secure: rhc1UznYFD+KsDfuFnDikzExkCLFhifw7Dud8AflcsS/whNI7pgy7sXacktuwtQUEKlEBfWQ7HCGCmaM6Q6ZuoWcJro28vCZVV+RTRfOZuIITh71QhkN8l4J3xY+l1IoLGnU0KlGSo2z0sguukheDXaKKMW2WUQTrOV6/a6J8pb6WIDBDyf7xYeOQ+k4uxaHsMG6Y5sHSuOG9pNnmDUoozC9YCAZYvZ9Y54w5gD1QCvaxR7vz6lK/KTZqB+lR6ectjDENBifhC0e1UaKT6CP6AqiRZ/OxWKtNI6xodrEmc4sWOI5r8lSj2ui8FeWvV8k7kduL25fOsYvIBHvL2dlotLYdBEWHrCrrDhqDcxIV1Tu8lgZMy1S5XiYG+f6X2gQcZwXykE1C1iAGzMZFo++t7uYKXnhXKfbe1/hDbcgrrZ/viFLA/QtbvZBGFr5rGt9fORrnL/YZ2aTkvxMLMTC1KfeA4tq+jmjHPEhM4/o3AVaQ4NJk95zW34ib+wobDwTgOMUwXTePBeFS4BtnazKV1084Bya3CmFix0bhLCml8F24+oYYSpXH+8wT9AcDIr0f+7Y6AKpcDP+gAcwtcGIrAZ2SrGckBcMqvQHSmnga01OecUiR23wq8+xv+EiBn+AO9dI29+qahLTLg2RFR98kkqTzHY0OIAMURiH2ua5Tcg=
