language: node_js
node_js:
- 8
script:
- yarn lint
- yarn build
deploy:
  provider: script
  script: yarn release
  on:
    branch: master
    tags: true
env:
  global:
    - EXTENSION_ID=eogckabefmgphfgngjdmmlfbddmonfdh
  matrix:
    - secure: nwCyjzpPT3X6zpqVfL1NwL5KpdCgANHJG61BGIM/iZKWBF8JtAYodlSRcQnAmifJ25dJJHAmWA+tCtsm2LFiOmD7WJEOKim+SKWk4kqSPogXZ2sEdNcc7L01uj/GDKiM9Msn0ORdNITw46UowkFYkI2O/EwxQMjkz7tVG4PKc2k2ta7YjIPdYLR/yW4CpW1nWS0YX9Ys+hPdk7h0zaA8QIhQ/wS9QAVxNSq6S6jrFvZepJVA9zH5Q8b/H5fqgIeKXTQ40DXSvqglF6We384EZdLfvrp98mPRMdF4CIDmfP6owecU6h4QkP4zdNGnSAY1zHWs0kAPwXmH5+8HWcIAJwDa4iYMmTrQSgqZEEblCQW4WJ+RDIWuRM+woeGH9BvKnhqDEvXDm/QMdhlhVYArTgwm3Ne/pliyXpv37hrLqomZp4gsa/FIlJdTQRMo9ez4iNwdLehslRlxFxUIRsBXHSczb+EyT3yl9x75uu17oXDIlqIQVWUUhhVa2Hm/BML3iO2ijhWrDzbeMW2gQyTKZOfVBKfzb1NmWN3LpnkdkUDUcd+1nAmHsu0UDZsEPcketZaCqOmxDAPWlJfNXCXRQFNr7S1X//bnNi+StEL24qcZG7apxUJuFbQh2K0wYWNbYq+EicAkRr3Hw60V/rnW2giYO8ZaL+mg8mRN5dA3zjs=
    - secure: dKzoLKb2tUXjbIHYiCEc/TeXOB1oWNPfTraS7V7E7t9izRd35Uu4v1anwXbF+7sC+cb5dGr1241ZbG14mwpWJcF9MCbeogut7ergeLGZVDwbfHwxQslrtC18Xgnyw/2NZHXWraFoCZ0qpzyqJxGdlmkDKdxp+PRHAoOwyodnL9cHlEXMUAlBmq08nEy4UTWuutfH+B9zLczCetM9G1Fe4puIjUsUaWu59+wWaM4jG5RVpii5dxcxMsQlP8rfCnPl/91x6zklAlJWdwhwxzI2jf2mLXMPXHLgTnz3oiFG+W5NqXRGcDxJidW3Sor3wdka0jJLo0ILSNi7+i45/ygeGlAcxFgsxZEufm4bZ6LCM/gAQ3X60IovafUb1Fy1i9394yksWRwxZcNx4PSDYDTRJt6VafwCE4JdfY4BHOl0n3Qhk/F8sXBqqctzjCcW0raGiXU5n062r79/VUTlKjo7N0WKlUebIntmqAL6dFXz+ixxRqXZDTk0thr04ZbapEafxCrOgfa2qpDW8IOwpS5UxR7wcaqQjVujq+5u4GKHW7Gct1/I36/n//nqhFlpIDFV5MjrPu0pT5NciYyS7iOrYl3j0BnzqFQZiW9DKqIS9aV1JU2RJI1SEmu47GAWc1y3n9o7BUuklbJVRo6DeDZ4oAwoScJOGscW8alNDN5vOmw=
    - secure: gtm7j+mbVifZTz89B5nFTb+o03qmTMEB36hl9IR1kH26r7x9OOJBOXJq5uW6L1po1K27bQ7UTGlhrkrnoLdWE2+nOpp/xLqqHsro2iwsfuwYfe8E+hnVFcS/fYTTYlOZBxdiNV6VPrWHmyJYnXVt7L5tJAsHzf2qoHSO4eU2kEnnkB0eowmCwolDGI4g2cjkDJxPm8pkHC9lfkCIHjNofz5SQ7OtN672UtG5XtQXataGoefWPL4TYR7jBXdpZ7ZJl4L4Le1YICOv4UO/XbIyiRMjh4E3RY8ic8Q28gSEeeegiWLgpo5oBkJNBRhs+xqDFivMLA7V4os0xbn+GhOkdGWcadPCloe7bPXw6DgGGkc5CXl+q16IuW/8NGlhVWLvzeXwyYDBsGwle/yohVOvAjzikWxox7dSCHNuiV4d9+6eBtOU3nZ3Vf1KLqCb1a/yzIiwBwivZMtMe6YaCqBAfLl9Z4FpVA6S2x4VdXsD+mIZT6S+1qPeacc7kyzc5uod9RSLU2/WUedngVCOXYZPxdteabAfjEB9/bAcoyGsoOIaSKCCmMECnlaeDtS0eIp26Q774bvjJWWZ3YOSZitFdz33lRWTWIGggaPpZdbuqmRBJOT+OH8ejHXam6vXphfEQ7JcaQnsklsHmvmGLOwjbpSIhMNnEyJmq+nNqtJ/BmY=
